### ISSUE TITLE
Memory mapping

### ISSUE THREAD

**Issue by Daniel-Abrecht** [WebAssembly/threads#103]
At the moment, there is only one continuous memory which is either shared or not, which corresponds to either an ArrayBuffer or a SharedArrayBuffer. But I think this complicates things a lot, and some things that are used in some programs aren't possible to implement the way it is now. For example:

 * Thread local variables would become a lot simpler. We could just map a SharedArrayBuffer for the shared memory to one address segment of the memory, and a different (Shared)ArrayBuffer to another one for the thread local memory, and just use a different one for the latter for the memory of each instance. The linker could know at which address which section starts using a linker script, like with any other platform.

 * Most mmap, mremap, shm_open, etc. functions related to memory mapping and shared memory are currently impossible to implement as specified by POSIX. For example:
    * Threads aren't the only way to write concurrent programs with shared memory, a program may want to allocate some anonymous shared memory with mmap and MAP_SHARED and then fork a few times. All forks would share this memory segment.
    * Programs may want to mmap a file, possibly even the same one. The file doesn't even have to exist, it could have been created by open(...,O_TMPFILE) (any current unix system), shm_open(SHM_ANON) (freebsd only), memfd_create() (linux only), etc. and may have been transferred by a unix socket, etc.

I'm mainly concerned about the things that aren't possible to implement the way it is now. As for the implementation, I would have something like this in mind:
```
var threadlocal = new SharedArrayBuffer(0x100000);
var sharedmem = new SharedArrayBuffer(0x1000000);

var memory = new WebAssembly.MappedMemory({
  memory: [
    {buffer: threadlocal, offset: 0x0},
    {buffer: sharedmem, offset: 0x10000000}
  ],
  page_size: WebAssembly.PAGESIZE_DEFAULT // or WebAssembly.PAGESIZE_SYSTEM_MINIMUM
});
```

Of course, I don't know how difficult this would be for browsers to implement, but I'm pretty sure it's possible. However, I think it may make sense to make a few restrictions, like only allowing SharedArrayBuffers or something similar, for example.

I don't really have time to work out the details, and it's probably not that important for most applications. It's just something I thought would be nice to have, so I wanted to share the Idea.

Edit: This may be similar to #84, even though not necessarily the same.

**Comment by conrad-watt** [comment]
If I'm interpreting this correctly, this proposal is similar to allowing a Wasm module to declare multiple memories, which could individually be labelled as shared/local (you referenced #84).

This is a [planned future feature](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#multiple-tables-and-memories), and the [reference types proposal](https://github.com/WebAssembly/reference-types) is the first step towards implementing it.

It's clear that the current MVP doesn't support some real-world patterns efficiently. I don't know how much thought has been given to handling fork, for example.

**Comment by dschuff** [comment]
I don't think multiple memories really serves the same use case though; the use case here is really to have different mappings in the same memory space (which could also be useful independent of threads). General memory-mapping capabilities are something we have thought about in the past (see [future features](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#proposals-we-might-consider-in-the-future)), likely split into more granular capabilities than the swiss army knife that is `mmap` today. But there's not been a specific proposal for it.

**Comment by conrad-watt** [comment]
Ah, I didn't properly get how MAP_SHARED works, and was focusing to much on the first bullet point, which only requires statically shared/local segments.

It's interesting to think of how this would work with exporting a Wasm memory to JS. What would the expectations be, I wonder, around creating a {Shared?}ArrayBuffer out of map_shmem (from the future features link above) mapped memory? The sketch above seems to suggest a new top-level memory type, "mapped", alongside "shared", and regular, which exposes segments as separate components.

**Comment by Daniel-Abrecht** [comment]
Yes, exactly. If I understand things correctly, a memory can have multiple data segments, which correspond to linker sections? If a memory can be either regular (ArrayBuffer), shared (SharedArrayBuffer), or mapped (MappedMemory), I think an exported mapped memory would just be a MappedMemory object. On current unix like OSs, when a program is loaded into memory, all memory is initially mapped as MAP_PRIVATE as far as I know. So if a module exports memory, a single SharedArrayBuffer containing all the memory needed by the data sections and exposed using the MappedMemory would be sufficient. I wouldn't export different SharedArrayBuffers for each data section in that case, because I'm not sure if data sections/linker sections could overlap. That would also mean that in addition to an offset at which an array buffer is mapped in a MappedMemory, an offset from which the array buffer is mapped as well as how many pages are mapped would become necessary. There would also have to be some checks when constructing the MappedMemory that the offsets are properly page aligned. Since I don't know how browsers handle ArrayBuffers and SharedArrayBuffers internally, would those need an option or something so the browser knows that they may be used in a MappedMemory, or can they copy and realign the buffers or even always make sure they are page aligned? In the worst case, a non-growable Memory object would have to be used instead of an ArrayBuffer.

I hadn't seen the  planned future features before, they are very interesting. When I proposed the MappedMemory, I was thinking about things with allowing a user defined run-time to handle things such as creating memory objects and so on, just like syscalls aren't handled by the webasm implementation itself at the moment. But looking back on that assumption and the existing future feature request, I realize I missed a few things:

Having to construct a new MappedMemory to have a new memory mapping would allow it to be immutable and be used similar to how a shared Memory object could be used by different instances to simulate threads, but I now see that that alone wouldn't work. If an application would call mmap, and I would construct a new MappedMemory and a new module instance, I would loose the current stack, which is an issue that didn't exist with a different thread which would have a different stack, and I would still have to return from the callback to the instance with the old mapping, except if I throw an error or something, but then I would still loose the current stack. It's a similar issue as with fork and setjmp. Looking at the proposed map_shmem, it seams like it was intended to update an existing memory object? I think that would work in that case. But it kind of boils down to how much should be done by the browser implementation and abstracted away, and how much is handled by the user/their runtime. I think the issue of maintaining resources and states like the program stack across different module instances and threads will probably come up again in the future, so maybe that should be solved before deciding how to implement memory mapping.

I've also seen the map_file idea, which would map a Blob, but I think that could be problematic because a Blob can consist of files, buffers, etc. and making sure all pieces are allocated or reallocated page aligned so they can be mmaped may be difficult and may require copying a lot of memory.
