### ISSUE TITLE
Rename *.atomic.wake to *.atomic.notify?

### ISSUE THREAD

**Issue by binji** [WebAssembly/threads#104]
JavaScript recently renamed `Atomics.wake` to `Atomics.notify`, see https://github.com/tc39/ecma262/pull/1220. Should we do the same for the WebAssembly atomics instructions?

**Comment by aheejin** [comment]
[We named those instructions in `atomic.wake` and `atomic.notify` in LLVM backend](https://github.com/llvm-mirror/llvm/blob/70de09a348124adaa8041c8ebba546cc6e93e8bc/lib/Target/WebAssembly/WebAssemblyInstrAtomics.td#L915-L938), to be consistent with JS, which of course does not have to be the same with real wasm instruction names though, as long as the binary opcodes are the same. So overall I'm in favor of the change.

**Comment by sunfishcode** [comment]
(I don't have an opinion on *which* names, but with @aardappel's work, the LLVM wasm backend has been moving in the direction of harmonizing its text assembly format with the official wat format, so we really should use the same names, whatever they are, since that's the easy part :-)).

**Comment by rossberg** [comment]
I have a slight preference for keeping `wake`, since it seems more common, its meaning is a bit more intuitive, and wake/wait makes the aesthetically nicer pair. :)

**Comment by aheejin** [comment]
I guess we can close it now, after we decided to use `*.atomic.notify` in the [Nov 13 CG meeting](https://github.com/WebAssembly/meetings/blob/master/2018/CG-11-13.md#revisiting-the-edge-case-semantics-of-wake).
