### ISSUE TITLE
Encoding Scheme

### ISSUE THREAD

**Issue by binji** [WebAssembly/threads#12]
Any thoughts on the proposed encoding scheme? The current proposal uses a prefix byte and takes ~120 of the 256 codes in the prefix space.

There's currently an alternative proposal which requires adding i8 and i16 value types (see https://github.com/WebAssembly/design/issues/1049).

Any other ideas?

**Comment by lukewagner** [comment]
We were talking about this in the context of SIMD and thinking it'd be nice if there was a regular scheme, for whenever we a prefix byte was used that, after the prefix, there was a LEB128.  That way we "bound" the ad-hoc-ness of our encoding scheme.  It also seemed nice to have the prefixes start at the high bytes (0xff) and count down.

**Comment by binji** [comment]
> We were talking about this in the context of SIMD and thinking it'd be nice if there was a regular scheme, for whenever we a prefix byte was used that, after the prefix, there was a LEB128.

Ah, I like that idea. Though for either encoding proposal currently, there aren't enough opcodes to make a difference just yet. :)

**Comment by stoklund** [comment]
If we want all opcodes to map into a 32-bit domain, it is still possible to adopt something like the [SQLite variable length encoding](https://github.com/stoklund/varint).

**Comment by jfbastien** [comment]
I advise listing a bunch of possible encodings, listing pros / cons, and polling each.

**Comment by binji** [comment]
We agreed in the CG meeting to the following:

* Use a prefix byte for atomic opcodes
* The prefix byte is `0xfe` (`0xff` is reserved for future expansion)
* After the prefix byte, the encoding is LEB128
