### ISSUE TITLE
Text format of atomic.fence

### ISSUE THREAD

**Issue by aheejin** [WebAssembly/threads#143]
Should we include the 'order' field in the text format of `atomic.fence`, like
```wast
(atomic.fence 0)
```

Or not?
```wast
(atomic.fence)
```

@conrad-watt @lars-t-hansen @binji @sunfishcode

**Comment by lars-t-hansen** [comment]
Does that need to be fixed now?  We eventually need a solution for the text format for all the other atomics too.  So whatever we do, the absence of an order will need to mean seq_cst, and fence can be fixed when we fix the others.  And fence currently takes no other parameters and so there would be no room for confusion.

(Obvious fixes include opcode suffixes, eg `atomic.fence.seq_cst` and keyword arguments, eg `atomic.fence seq_cst`.  I think numeric arguments are probably not what we want.)

**Comment by rossberg** [comment]
Agreed with @lars-t-hansen, I don't think this requires any change right now. Adding keyword arguments to all respective instructions later seems like the most desirable way to extend this once necessary.

**Comment by aheejin** [comment]
I was working on some tests (for toolchain support and also possibly for spec tests later), so I was wondering. I'll then write it as just 
```
(atomic_fence)
```
tentatively without arguments. We can add more later. Closing.
