### ISSUE TITLE
Unordered initialisation from data segments

### ISSUE THREAD

**Issue by rossberg-chromium** [WebAssembly/threads#16]
The overview currently says about initialisation from data segments:

> When the imported linear memory is shared, the writes are non-atomic and are not ordered.

What's the rationale for unordered? Is that necessary or desirable? It would make data segments significantly more non-deterministic than everything else proposed. Unlike with a general memcpy operator the memory regions cannot overlap here, so isn't it easy enough to guarantee an ordering?

**Comment by lars-t-hansen** [comment]
Don't know about the motivation for that language, but if the writes are not atomic, they may appear unordered to another observer anyway.  If another observer wants to observe them predictably some sync after initialization will make the order of writes moot - the writes will all be visible to the observer at that point.

**Comment by rossberg-chromium** [comment]
I see, makes sense.

However, is there actually a way in this proposal to synchronise after such initialisations? Since they are not performed by user code, how could sychronisation be expressed in user code? Would it be sufficient to synchronise in the start function under the given memory model?

**Comment by lars-t-hansen** [comment]
If the backing buffer is distributed to workers after initialization has run then synchronization should be implicit in that operation (per the ES spec).  But if the backing buffer is distributed before initialization, it should be enough for the initializing thread (which presumably must start first) to write a word atomically at the start of its operation and for the other threads to atomically read that word when they start and observe the correct value there.

That said, this all probably depends on who performs initialization in a multi-threaded setting, and when that happens, and how it's controlled.  I confess I'm not completely clear on that, yet.

**Comment by jfbastien** [comment]
Consider a case where:

1. Create a WebAssembly.Memory with the shared attribute
2. Instantiate a module with this memory
3. Much later, instantiate a different module with the same memory

When we do 3. there can be data segments which get initialized, and the instance from 2. can notice that initialization.

The intent of the proposal is that all data segment initialization is non-atomic, and that once that's complete the initialized writes are guaranteed visible (they happen-before 3. invokes the start function). This means that data segment initialization needs not be performed with atomic writes and need only use a single barrier (after all segment initialization is performed, or before an exception is thrown because OOB segment).

Maybe the proposed wording doesn't actually do this?

It also sounds like @rossberg-chromium isn't sure these are the right semantics. Would you instead rather initialize all data segments atomically? At which granularity? "Byte or more" sounds simplest. Maybe this can be another poll for the meeting.

@binji can you clarify the wording as above, and if @rossberg-chromium agrees also add a poll?

**Comment by binji** [comment]
@jfbastien Yes, I'll clarify.

**Comment by lars-t-hansen** [comment]
Actually I think I'm additionally confused...  The spec says "When a module has an imported linear memory, its data segments are copied into the linear memory when the module is instantiated."  Is this meant to say that when I instantiate one module on a memory, and do some computation there, and later instantiate a clone of the same module on the same memory (in another worker), the latter instantiation will overwrite whatever changes the first instance has made to the memory?

**Comment by binji** [comment]
Oof, yes. This is problematic, and I hadn't considered it. Unfortunately, I don't believe we have a mechanism for resolving this currently.

**Comment by rossberg-chromium** [comment]
@lars-t-hansen, yes that is the case. You can basically emulate a memcpy into a memory at arbitrary time by creating and instantiating a module with a data section applied to a memory import. That's the broader reason why I'm bringing this up.

**Comment by lars-t-hansen** [comment]
OK, so I suppose if we take memcpy as our model, the way this would have to work in practice with shared memory is either (a) we pass a flag to the instantiation to say "do not do the memcpy now" and pass that in all but the first instantiation, or (b) we have a separate Module that contains only the data segments and we instantiate this once on the shared memory, before instantiating the code Module(s) separately as we need to.  (And then in either case there's the happens-before relationship that @jfbastien described to make sure the initialization is visible everywhere.)

**Comment by jfbastien** [comment]
> we pass a flag to the instantiation to say "do not do the memcpy now" and pass that in all but the first instantiation

That seems odd. It's up to the user to decide how memories are shared, and whether modules instantiated use data segments. In that sense the flag you propose already exists: just don't do that if you don't want to!

I would standardize:

* Data segments are initialized in their definition order
* From low to high bits
* At byte granularity (which can be coalesced)
* As non-atomics
* An entire module's data segment initialization then synchronizes with other stuff (effectively, followed by a barrier)

**Comment by binji** [comment]
> That seems odd. It's up to the user to decide how memories are shared, and whether modules instantiated use data segments. In that sense the flag you propose already exists: just don't do that if you don't want to!

Yes, but the common case is that you'll want to have one module shared between workers and instantiate the data segments once. Shouldn't we have a convenient way to do this without requiring the developer to create a separate module for the shared data segment initializers?

> I would standardize: ...

These make sense to me.

**Comment by lukewagner** [comment]
Ooph, good point.  Existing asm.js+SAB usage hasn't hit this b/c asm.js doesn't have data segments and so Emscripten pthreads support uses .mem files to init memory.  

In the limit, with pure wasm threads, we *will* have a single `Instance` shared between threads so there will only be one instantiation and one memcpy of the data segments.

For now, with worker-based threads, we could just say that Emscripten has to emit .mem files (like it used to do anyways).  But if we really wanted to avoid that, it seems reasonable to add a third property-bag argument to `instantiate` that allows opting out of data segment initialization.  I'm pretty sure some other uses for that property bag will emerge

**Comment by jfbastien** [comment]
Or users / toolchains can split off the data segment module from the code module(s)?

**Comment by rossberg-chromium** [comment]
On 29 May 2017 at 21:19, JF Bastien <notifications@github.com> wrote:

> I would standardize:
>
>
>    - Data segments are initialized in their definition order
>    - From low to high bits
>    - At byte granularity (which can be coalesced)
>    - As non-atomics
>    - An entire module's data segment initialization then synchronizes
>    with other stuff (effectively, followed by a barrier)
>
>

Sounds good to me.

**Comment by lukewagner** [comment]
@jfbastien Right; probably equivalent in perf too.  Maybe other stuff like static constructors could be factored into this "init" module as well.

**Comment by RyanLamansky** [comment]
Splitting up a WASM to get around the multi-thread repeated data initialization problem is an ugly workaround, in my opinion.  An opt-out parameter is an acceptable solution, but some kind of natural awareness is preferable.

**Comment by binji** [comment]
Updated text in the PR above, please re-open if there are further issues to address.

**Comment by binji** [comment]
Sorry, it seems I shouldn't have closed this as there was still discussion around whether to provide a flag to prevent data segment initialization. I thought this came up in a CG meeting, but it appears not (at least I was not able to find it in the notes).

**Comment by binji** [comment]
Hm, actually, I guess this has moved to #62 now so I'll just leave this one closed.
