### ISSUE TITLE
Odd milliseconds vs nanoseconds discrepancy in the Atomics.wait API

### ISSUE THREAD

**Issue by juj** [WebAssembly/threads#175]
The functions `Atomics.wait()` and `Atomics.waitAsync` use timeout values in millisecond units:
 - https://tc39.es/proposal-atomics-wait-async/#sec-addwaiter

However, the same Atomics wait operations on the wasm side via `memory.atomic.wait32` and `memory.atomic.wait64` specify timeout values in nanosecond units:
 - https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md#wait-and-notify-operators

This inconsistency feels a bit odd, so wanted to double check if that was intentional in the spec to utilize the different units?

**Comment by conrad-watt** [comment]
It was a deliberate decision a while ago, you can read the previous discussion here
https://github.com/WebAssembly/threads/issues/36

One of the posts in that issue has a dead link to the relevant meeting notes, here's the fixed link
https://github.com/WebAssembly/meetings/blob/master/main/2017/CG-07.md#threads

**Comment by juj** [comment]
Thanks for the quick answer, very informative thread, and looks like it was deliberate indeed.
