### ISSUE TITLE
Initializing shared memories (within a module).

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/threads#178]
I cannot find any information about initializing shared memories within a Wasm module, only importing them from the host.

Given that a module can define, import and export unshared memories, and can import shared memories, it seemed natural to assume that a module could also initialize, then export, a shared memory, permitting the host to pass the memory to other threads, where it can be imported into other modules *et cetera*.

I cannot think of a reason why permitting this would be a non-starter, but cannot find any discussion where it was considered either. I'd be grateful if somebody could explain the situation, as I'm certain I must've missed something. Thanks.

**Comment by conrad-watt** [comment]
If a module declares and exports its own shared memory, that memory will be populated by any active data segments the module declares targetting that memory before it's exported. Also, the `start` function is run before the memory is exported, which is another opportunity for initialization. So this should be possible already (the initialization is essentially the same as for non-shared memories).

**Comment by 7ombie** [comment]
I see, though it wasn't the initialization I was confused about. I didn't even know that it was legal to create a shared memory within a module. I could only find examples of it being created by the host, then imported into a module, so was really asking about the basic ability *to* initialize a shared memory, rather than the specifics of *how* it's initialized.

**Comment by conrad-watt** [comment]
@7ombie there's an example here (https://github.com/WebAssembly/threads/blob/master/test/core/atomic.wast#L4) of a module declaring its own shared memory - is this what you're looking for?

**Comment by 7ombie** [comment]
Yes. Thank you. I really am sorry for asking so many questions in the issue tracker. I am trying to figure things out first, and there's nowhere else to get help. Thanks again. Much appreciated.

**Comment by conrad-watt** [comment]
No worries, thanks for your interest :)
