### ISSUE TITLE
Atomics

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/threads#181]
Greetings, are the atomic operations only atomic between each other, or they are atomic in relation to the non-atomic writes as well. What I mean is that if one thread is performing an atomic operation, lets say cmpxchg, is it guarantied that another thread will not use a non-atomic i32.store and corrupt the atomic operation? Maybe I'm missing something, or its an issue.

**Comment by lars-t-hansen** [comment]
To the contrary, this type of race has the effect of making the atomic operation non-atomic.  See eg https://tc39.es/ecma262/#sec-shared-memory-guidelines, Note 3: "the memory model effectively demotes the atomic operations involved in a race to non-atomic status."

**Comment by conrad-watt** [comment]
Just to add, the behaviour Lars is describing works because in a C++-like language, such a race would be undefined behaviour anyway. So our behaviour in this case is strictly stronger. In fact, doing anything much stronger would likely require atomics to be compiled to more expensive instruction sequences.

**Comment by verbessern** [comment]
That is exactly what I have described (with less precision, because you know more): "making the atomic operation non-atomic" = "corrupt the atomic operation". From the text "That mapping is correct **so long** as an atomic operation on an address range does not race with a non-atomic write..." I assume that my question was valid, and from the text "the memory model effectively demotes the atomic operations involved in a race to non-atomic status" it seems that this a defined behavior = the atomics are not atomics in this case. I would assume that the undefined behaviour in C++-like language in practice will be that the atomics are also not atomics in the same case.

Thank you for the references and the explanations.

**Comment by verbessern** [comment]
Btw, I think that at the current stage of wasm, its not possible to be in this state, because the shared memory is always accessed with actions, and each action is atomic by default. The only problem would be if a thread accesses a shared memory as it is a local memory, but that seems not possible (at least because there is only one memory). With other words, if a thread uses an atomic operation on a shared memory, the only way to demote the operation to non-atomic is another thread to access the same memory by writing to it in the same time and overlapping offset non-atomically, that is not currently possible.

**Comment by conrad-watt** [comment]
>  I assume that my question was valid

Yes, it's a very sensible question, and exactly the kind of thing we have to think about when designing this extension :)

> Btw, I think that at the current stage of wasm, its not possible to be in this state, because the shared memory is always accessed with actions, and each action is atomic by default.

If you mean Wasm without this threads proposal, yes it wouldn't be possible.

**Comment by verbessern** [comment]
No, I mean **with** the thread proposal. The shared access is guarded by events. For example the t.store?N (page 80, pdf), ensures that the shared memory is threaded differently then the unshared. 4.2.16 states that all actions are atomic per instruction. That for me means that the access to the shared memory is already synchronized. The only way to "interrupt" the actions is one to write to the same memory by accessing the bytes directly from another thread. But that is impossible, because t.store?N point 14 forbids that.

**Comment by conrad-watt** [comment]
Ah, there's some imprecise wording in the spec. Actions are always "atomic" in the sense that they are indivisible (even if they both read and write, e.g. `cmpxchg`). Actions can be generated by both non-atomic and atomic accesses, however the actions generated by atomic accesses normally come with even more guarantees than this (e.g. "sequential consistency").

In the presence of a racing non-atomic, the actions generated by atomic operations lose these stronger guarantees, but keep the "indivisibility" which is guaranteed of all actions - i.e. they behave like the actions generated by a non-atomic operation.

**Comment by verbessern** [comment]
This does not change the situation. If all actions per instruction are indivisible, that means that its impossible one to generate an action that will interleave with another action. Are the actions "atomic" or not is irrelevant then, when they are in generally sequential = the internal steps of an action cannot be interleaved with the steps of another. Yes, the atomic actions cannot be reordered, because of the sequential consistency.

I will express with an example: thread "a" does (1) Read (2) Modify (3) Write; thread "b" does (4) i32.store on the same address. Both of the threads have by 1 action, the first one made of 1-2-3, and the action of thread "b" made of 4. Both threads will request this actions to be performed on their shared memory. Because this actions are always indivisible, its impossible to have 1-4-2-3 (or 1-2-4-3) steps over the shared memory. It will be either 1-2-3-4 nor 4-1-2-3. That is guarantied by the indivisibility. But from it follows that on web assembly its impossible to "making the atomic operation non-atomic". 

As I said earlier, it would be possible if one of the threads is using the shared memory, as its a local one (i.e. thread 'a' uses the "else" of t.store?N point 14 , and thread "b" uses the "then"). Then 4 could be performed at any time, but that is impossible at the moment.

As far as the shared memory is always modified by actions (non atomic or atomic), web assembly guaranties "non-racing on shared memories = indivisibility of the actions" and guaranties the order of the atomic instructions by "sequential consistency".

The order of the access to an unshared memory becomes irrelevant, because it is used by a single thread (I presume). If unshared memory is used by more then one thread, then everything can happen (1-4-2-3 becomes possible, and "making the atomic operation non-atomic" becomes active).

Apologies for the long post.

**Comment by verbessern** [comment]
To be as you claim, then the indivisibility must be only guarantied for the atomic actions, not for the non-atomic actions as it is now. That will mean also that the t.store?N instruction must use the "then" for the non-atomic access for shared memories as well, and  the "else" only for the atomic instruction on shared memory.

**Comment by lars-t-hansen** [comment]
All actions per instruction need not be indivisible.

As a trivial example, a legal implementation strategy for wasm atomics is to have a global lock (in some memory that is private to the implementation) which the runtime acquires when it wants to perform an atomic RMW operation on shared memory.  Having acquired the lock the thread performs the atomic operation using non-atomic primitive operations, and then releases the lock.  Other atomic operations will also take the lock and thus order sensibly with the first atomic operation, but non-atomic operations will not take the lock and may thus scribble on the locations that the atomic operations operates on while the atomic operation is in flight, destroying eg partial results.

For example, a CPU that has only 32-bit primitive atomic operations may use this strategy to implement 64-bit atomic RMW operations, as does the MIPS32 port of SpiderMonkey (the wasm engine in Firefox), see https://searchfox.org/mozilla-central/source/js/src/jit/mips32/MacroAssembler-mips32.cpp#2569.

**Comment by verbessern** [comment]
This is only valid if the memory pointer does not move. If the memory pointer moves, then the non-lock operation might as well crash the executable if a grow operation happens to take place in the same time (i.e. if the growth changes the memory pointer, clearly the other thread might access the invalid old memory). However this is quite a hard requirement for the implementations. Then yes, it is possible to scribble the memory in this way. 

This is also a problematical requirement, because allocating extra virtual memory, even uncommitted, still is accounted by the total amount of available RAM + Page File. Then if the maximum memory for a module is 512MB, one might not be able to start even few on a client's machine, even if they actually use "usually" just 25 MB, for example. This is like to say that, lets start each executable with 512MB virtual memory for the thread dedicated stack, "just in case".

If the memory pointer moves "on grow", then a lock is not a recommendation, but a requirement. If one already has the lock, might as well just do its operation non-atomically for all atomic operations. In this case because the lock is always held for all operations, it is impossible for any thread to scribble the memory. Then one might start with 25 MB minimum requirement, and grow dynamically "on demand". But in this case the lock is mandatory, because of the pointer, and I'm right, that its impossible to scribble the memory. That is a good thing, assuming its true, because there can be no scribble. But locking the whole memory length per access, is probably a performance hit.

So in the end, if the memory moves, extra virtual memory must be reserved for the maximum needed, else locking per access harms the performance. What is going to be, use **extra** memory or have **less** multi threaded speed? Are they both valid? Technically yes, if you use extra memory, you are "per specs = speed + scribble" if you use movable memory, you are "per specs = slow + no scribble". Right?

**Comment by lars-t-hansen** [comment]
SpiderMonkey does not move shared memory blocks because of hazards of this type.  I doubt that will change.  (I don't know what Chrome does.)  In turn this leads us down the path to pre-reserving shared memory blocks up to the declared maximum.  This is painful if your system does not have VM overcommit or very low VM limits, but it's the bargain we have accepted.

**Comment by verbessern** [comment]
Understood. Thank you. There is no issue then.
