### ISSUE TITLE
Spec draft text format for memory type inconsistent with tests

### ISSUE THREAD

**Issue by takikawa** [WebAssembly/threads#184]
The draft spec at https://webassembly.github.io/threads/core/text/types.html#text-memtype shows the `shared` modifier for memory as starting a new nesting level:

![image](https://user-images.githubusercontent.com/64192/144329756-811f1a05-59d6-4385-a966-0c9970727cd3.png)

However, this doesn't match the examples or tests where `shared` is just a keyword that can come after the limits.

e.g., `(module (import "spectest" "shared_memory" (memory 1 2 shared)))` from https://github.com/WebAssembly/threads/blob/main/test/core/imports.wast#L499

**Comment by rossberg** [comment]
Thanks, I fixed the grammar.

**Comment by rossberg** [comment]
Hm, I had to search for it. Seems like I still [committed](https://github.com/WebAssembly/threads/commit/b438715e7edfb026dc8945f47e5fc18edf26ecbf) it to master at the time, but somehow it never reached main. No idea why. I just merged it over manually.
