### ISSUE TITLE
Consider restricting wasm to safe concurrency

### ISSUE THREAD

**Issue by DLehenbauer** [WebAssembly/threads#2]
@rossberg-chromium suggested I pose [this question](https://github.com/WebAssembly/gc/issues/4) here as well:

What is the sentiment for restricting wasm to [safe concurrency](http://joeduffyblog.com/2015/11/03/a-tale-of-three-safeties/)?  (Either as a starting point, or as a verifiably safe subset.)

The primary restriction is that memory can either be privately held by a single agent and mutable, or immutable and shared between agents, but never both mutable and shared.

**Comment by AndrewScheidecker** [comment]
Languages like Rust are compelling points in the design space of programming languages, and make trade-offs that are likely a practical win for many kinds of programs. The fundamental trade-off is that they stop you from doing stuff you can do in C that you probably didn't mean to do; but sometimes you *did* mean to do that, and it's just not possible in Rust!

Given that the unsafe shared memory model that current hardware implements can be used to implement the Rust safe shared memory model, it doesn't seem worthwhile to try to find a safer subset of hardware capabilities.

**Comment by DLehenbauer** [comment]
You're right.  Forbidding unsafe concurrency would be too limiting.  I meant to suggest safe-concurrency as a either a starting point, or a verifiably safe subset, but got a little overzealous with the title.

Probably the least confusing thing to do is to close this issue and start a new one.
