### ISSUE TITLE
Lying to is_lock_free

### ISSUE THREAD

**Issue by RyanLamansky** [WebAssembly/threads#20]
Responding truthfully to `is_lock_free` may lead to undesirable behavior, as the program will follow a different path than it might otherwise have chosen, potentially exposing bugs or even aborting intentionally.

An implementation may want to offer the option to lie to `is_lock_free` so that a program such as the above will at least function, albeit with reduced performance.

I don't expect this to be an issue for native browser-based implementations, but some platforms don't provide the necessary primitives to perform lock-free operations on unstructured memory addresses.  The [.NET Standard-based implementation I'm working on](https://github.com/RyanLamansky/dotnet-webassembly) is one example, and I expect other higher-level implementations to face the same problem.

Should the specification mention this?

**Comment by jfbastien** [comment]
Two cases:

1 .Saying something is lock-free when it isn't can lead to bad performance at best, and deadlocks at worst (especially when we add signal handling).
2. Saying something isn't lock-free when it is might cause static assertions and compilation failures, or compile-time code selection which performs worst.

Which one are you suggesting? IIUC you're thinking of implementing WebAssembly VM in .NET, and its lack of general lock-free operations is biting you? Is that purely in linear memory? If so, it sounds like you're suggesting 2.?

**Comment by RyanLamansky** [comment]
I'm forced toward option 1 should the need arise.  I agree that avoiding deadlocks will be tricky 🙄

.NET Standard offers a useful set of lock-free options via the [Interlocked class](https://msdn.microsoft.com/en-us/library/system.threading.interlocked_methods.aspx), but there annoyingly aren't any options for raw pointers, which is how I've implemented linear memory currently, and even if I were to find a way around it I'm still missing options for xor/and/or/i8/i16/f32...

With .NET Classic, I could mix in some C++ to use intrinsics to solve all of these problems, but then I'm Windows-only.  .NET itself could be updated to add the needed features, but even if I wrote the code and pull request myself, it wouldn't be merged without significant demand.  WebAssembly becoming extremely popular would help 😉

Correct execution is my goal, even if performance is total garbage for cases like this.

**Comment by rossberg-chromium** [comment]
Not sure I follow. If we allow it to lie, what's the benefit of having this operator in the first place?

**Comment by RyanLamansky** [comment]
Lying is similar to quirks mode in a browser, or a compatibility mode in Windows.  It's ugly, but For The Greater Good­™.

Unlike those examples, this spec will be fully designed from the start, so in theory WASM app developers should get it right.  My concern is that since it's likely that only web browsers will be tested--and I expect all web browsers will ship with full native support for every opcode--fallback logic will be buggy or non-existent, forcing an exotic platform like my little experiment into less wholesome solutions.

I'm not asking for a spec change (if I were, I might point out that the answer to `is_lock_free 4` is _sometimes_ for me (assuming I find a workaround for my earlier Interlocked raw pointer problem)), just perhaps some kind of note that a WebAssembly implementer may choose to lie to this opcode in response to application misbehavior.

**Comment by jfbastien** [comment]
You're already allowed to be a non-compliant WebAssembly implementation, I'm not sure we want to list all the non-compliances you can choose.

**Comment by RyanLamansky** [comment]
Sounds good.

**Comment by sunfishcode** [comment]
Is it possible to write a test to reliably determine whether an implementation is lying in its `is_lock_free`?

**Comment by RyanLamansky** [comment]
If the implementation does a very good job at it, I suspect not 😈

**Comment by jfbastien** [comment]
In C++ you could rely on properties of the lock shard implementation (if it's per-size / per-address in an interesting way), or cause a deadlock by using non-lock-free atomics in a signal handler. Not reliable, definitely UB, but statistically likely to trigger.

**Comment by RyanLamansky** [comment]
If there is to be an official comprehensive conformance test, this would be a good item to include.

**Comment by lars-t-hansen** [comment]
The rough consensus at the meeting yesterday seemed to be that `is_lock_free` disappears and that there will be no normative references to lock-freedom in the wasm spec.

**Comment by sunfishcode** [comment]
Also, the intention is that the rules will be sufficient for C++ implementations to have std::atomic's is_lock_free be true for relevant types.
