### ISSUE TITLE
Behavior when grow called concurrently

### ISSUE THREAD

**Issue by anuraaga** [WebAssembly/threads#224]
I couldn't find anything in the spec that documents how memory grow is intended to be handled if multiple agents call it concurrently.

I see some mention of cumulative growth here

https://github.com/WebAssembly/threads/issues/26#issuecomment-306622940

But because grow returns the size of the old memory, I'm not sure if this means that grow calls still have to be serialized within the runtime. Otherwise, it seems that both calls may get returned the same size of old memory, which could lead to incorrect behavior in programs - size of old memory is generally treated as the "start of page" for the new memory, which would be shared by both callers. I think there are two approaches

- Serialize in the runtime, so the grow calls are handled non-concurrently possibly with a mutex
- Don't do anything in the runtime, meaning in most cases the guest must serialize, which dlmalloc in wasi-libc does, but it's unclear how general allocators may work. But this is closer to the behavior of `sbrk` FWIU, and perhaps is the intention for the grow instruction.

**Comment by conrad-watt** [comment]
There is a little subtlety here. All "direct" observations of memory size need to appear sequentially consistent, so the lengths reported by concurrent growths (and the overall effect on the memory size) must reflect some sequentialised order. In practical terms this means that the runtime needs to do some synchronization (e.g. possibly taking a lock) on each `memory.grow` and `memory.size`.

However "indirect" observations of memory size through bounds checks on instructions like `load` are only guaranteed to see concurrent growths that the guest has programmatically synchronized with the "indirectly observing" thread (e.g. through an atomic read/write pair). What this means in practice is that, (for example) in an implementation where `memory.grow` and `memory.size` need to acquire a lock in the runtime, `load` and `store` instructions (including atomics) aren't obliged to also acquire this lock.

All of this is currently specified in the draft specification (and some attempt is made to give intuition in the memory model's accompanying [non-normative note](https://webassembly.github.io/threads/core/exec/relaxed.html)).

**Comment by anuraaga** [comment]
Thanks for the notes and pointers.  So it sounds like the runtime does need to allow grows to be serialized.

> in an implementation where memory.grow and memory.size need to acquire a lock in the runtime, load and store instructions (including atomics) aren't obliged to also acquire this lock

Read through the non-normative note as well but still not sure so want to confirm, does this mean that in this situation the bounds check may fail due to a stale size

- Thread 1 calls grow, grow stores the new size with lock 1, thread 1 gets a pointer to the new page
- Thread 1 stores the pointer to memory with lock 2
- Thread 2 reads the pointer from memory with lock 2 and dereferences. Since lock 1 wasn't used, size is stale and below the pointer so bounds check fails

In wazero, currently we use atomic store of size in grow and atomic load of size in bound checks to assure visibility of the update but your description makes it sounds like this is overly strict. But if the above fails to bounds check on thread 2 it seems a bit weird to me.

**Comment by conrad-watt** [comment]
Assuming the locks in your example are implemented programmatically by the guest, if lock 2's acquire and release operations are implemented using Wasm atomic instructions, the pair of "thread 1 release" and "thread 2 acquire" on that lock is considered a sufficient synchronization and thread 2 _must_ see thread 1's grow (and thus the pointer check must succeed). This should work even if the runtime implements bounds checks using less-than-SC read and write instructions. To borrow C++11 terminology, it should be sufficient for the "bounds check load" of a Wasm `load/store` access to be implemented using a relaxed atomic (normally a bare platform asm load). To be clear `memory.size/grow` still generally need to use SC atomic accesses.

If thread 1 attempts to transfer the pointer to thread 2 without atomic synchronization (e.g. an erroneous guest-defined lock just using non-atomics), the spec doesn't guarantee that thread 2 sees thread 1's growth (and I'd expect weird behaviours to happen in practice in some implementations).

**Comment by anuraaga** [comment]
Thanks @conrad-watt - I had a model where only memory accesses within a lock are visible between threads but realize that any use of a lock between threads determines the ordering relationship between them, so lock 1 being the write lock for size doesn't mean that lock 2 won't cause it to become visible. Sorry, not super-deep on memory models so this has been really helpful to discuss, thanks.
