### ISSUE TITLE
Fix naming of new sign-extending operators

### ISSUE THREAD

**Issue by binji** [WebAssembly/threads#34]
See @rossberg-chromium's comment [here](https://github.com/WebAssembly/design/issues/1049#issuecomment-310403928):

```
Oh, I hadn't noticed these. I think the naming scheme is a bit off, since
the parts after the "/" are always proper value types denoting the operand
type elsewhere. It would be preferable to mirror the naming scheme used for
loads:

  * i32.extend8_s
  * i32.extend16_s
  * i64.extend8_s
  * i64.extend16_s

That would also allow you to include i64.extend32_s, which is currently
missing and not expressible in the above scheme (since it is ambiguous with
the existing operator).
```

**Comment by binji** [comment]
This is a good point. For clarity:

We currently have the following operators:

| name | result type | operand type |
| --- | --- | --- |
| `i64.extend_s/i32` | `i64` | `i32` |
| `i64.extend_u/i32` | `i64` | `i32` |

The new operators should be:

| name | result type | operand type |
| --- | --- | --- |
| `i32.extend8_s` | `i32` | `i32` |
| `i32.extend16_s` | `i32` | `i32` |
| `i64.extend8_s` | `i64` | `i64` |
| `i64.extend16_s` | `i64` | `i64` |
| `i64.extend32_s` | `i64` | `i64` |

When we discussed this in the CG meeting, we said we didn't need `i64.extend32_s` since we already have `i64.extend_u/i32`, but as you've pointed out, they are actually different. That said, you could emulate `i64.extend32_s` with `i32.wrap/i64, i64.extend_s/i32`, so perhaps we should skip it for now.

**Comment by rossberg-chromium** [comment]
I would argue that it would be odd that we cover this case for the load-extend operators but not for bare extend. Wouldn't the same counter argument apply to both equally?

**Comment by binji** [comment]
Hm, yes I suppose it would be a bit of a strange inconsistency. Though we're already breaking with consistency with the load/store operators for the atomic versions. But I agree that this isn't a good reason not to add `i64.extend32_s` to the proposal.

**Comment by jfbastien** [comment]
Can you note separately this change to make it clear that it's doing something different from in-person consensus, but document the reasons so any objections can be raised? I don't think there will be any, but we need to document *why* when we don't follow consensus, and we need to be very explicit about it.
