### ISSUE TITLE
Wording about future memory ordering

### ISSUE THREAD

**Issue by rossberg-chromium** [WebAssembly/threads#35]
The overview says:

"Currently all atomic memory accesses are sequentially consistent. This restriction may be relaxed in the future."

This wording probably is misleading -- it sounds as if we could make the same operators less strict in the future. However, once we standardise these instructions as providing SC, we will not be able to relax them later, since that would break existing programs relying on the strict semantics (we could only make them even _more_ strict). To relax the memory ordering semantics we'd need to add new instructions.

**Comment by jfbastien** [comment]
Agreed, the intended meaning is what you stated. No semantics change at the WebAssembly level, but you can recompile to get new instructions. That does imply a change for say a C++ program which used to have `acquire` / `release` operations which were compiled to `seq_cst`, and after a WebAssembly toolchain update could get recompiled to `acquire` / `release`.
