### ISSUE TITLE
Matching behavior of SharedArrayBuffers in ES spec

### ISSUE THREAD

**Issue by binji** [WebAssembly/threads#5]
The current proposal very closely matches the behavior of [SharedArrayBuffers](https://tc39.github.io/ecma262/#sec-sharedarraybuffer-objects) in the ECMAScript spec. The goal is to make it easier to match the behavior of existing JS engines. Is this a good goal for v1, or is there more we should do?

**Comment by lars-t-hansen** [comment]
Matching the ES spec makes it easy to reason about.  A superset of operations is not really a problem, but an "extended subset" type of situation should be a warning sign.  IMO.

**Comment by binji** [comment]
This issue is phrased a bit vaguely. The question that was actually polled was:
"Poll: include same atomic and threading primitives as ES except is_lock_free"

This was described as being the minimum; we later agreed to add additional functionality, including i64 atomics, etc. Those features are covered in separate issues.
