### ISSUE TITLE
tryLockMutex in example code

### ISSUE THREAD

**Issue by juj** [WebAssembly/threads#61]
Reading https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md, it first defines `lockMutex` and `unlockMutex`, and then has a line

```
(func (export "tryLockMutex") ... )
```

and then the example in the JS code has

```
        // Blocking on the main thread is not allowed, so we can't 
        // call lockMutex.
        if (instance.exports.tryLockMutex()) {
            ...
            instance.exports.unlockMutex();
        }
```

A couple of observations:
  1. There is nothing in the proposed implementation of `lockMutex` that would not be allowed on the main thread (that is, no `Atomics.wait`). I wonder if the comment there is meant more as a babysitting remark that developer would not do bad things? Or is it perhaps remains of some refactoring when `Atomics.wait` had been used in the example?
  2. The implementation of `tryLockMutex` would be good to be explicitly shown, so that developers understand how to go for the best practices. Perhaps the implementation of `lockMutex` could call the function `tryLockMutex` inside it to show the relationship of these easily.
  3. The example does mention about being naive, which perhaps a bit contradicts the goal of showing best practices; nothing wrong with using a spinlock as an example, I think it's very cleanly written here. However, it would be good to emphasize this naiveness by rewording the example from a `mutex` example to being a `spinlock` example, or a `spinlocking mutex` example, and write a tiny paragraph about what makes spinlocks different, and where they are applicable in comparison to appropriately sleeping mutexes/critical sections.

I worry that while the example might successfully handhold people from doing blocking waits on the main thread, that it might lead to some developers accidentally writing 100% spinning workers, if they mistakenly take this as a "canonical" example of how to write a WebAssembly mutex for web worker<->main thread interaction.

**Comment by lars-t-hansen** [comment]
@juj, there's i32.wait in lockMutex in that example, and that is definitely not allowed on the main thread in a browser.  It's not a spinlock.  (Spinlocks also don't work on the main thread.  Don't use them.)

**Comment by juj** [comment]
Err... Re-reading the doc, I see I have been super blind when reading the code. Very sorry for the noise!

**Comment by binji** [comment]
No problem, you made me realize it is probably better to write out the implementation of `tryLockMutex`. PR here: #63.
