### ISSUE TITLE
Creating Shared Memory in older engines

### ISSUE THREAD

**Issue by Cellule** [WebAssembly/threads#69]
The way Shared memory is currently spec'ed, trying to create a shared memory like so
```js
const mem = new WebAssembly.Memory({initial: 1, maximum:1, shared: true});
```
Would give you a normal unshared memory in older engines since we didn't know to look for property `shared`.

The same is true if the memory is created from the wasm binary with `(module (memory (shared 1 1)))` because older engines wouldn't know to looks for other flags in the [resizable_limits](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#resizable_limits).

Is this behavior desirable ?
If not, should we 
 - find a way to make it an error to try to create a shared memory in an engine that doesn't know about it 
 - give a method for the user to test if the engine can create a shared memory ?

**Comment by lukewagner** [comment]
According to the [spec for Limits](https://webassembly.github.io/spec/binary/types.html#limits), only `0x0` and `0x1` should validate as the flags field, anything else should be a validation error.  If that doesn't work (b/c engines are too permissive), using an atomic op should fail `WebAssembly.validate()`.

**Comment by jfbastien** [comment]
What Luke said is my understanding. It leaves us in the position where one can create a regular memory in JavaScript when they asked for a shared one, but then they can't do anything useful with a shared one and would fail if they tried. That seems fine.

**Comment by Cellule** [comment]
Sounds good, I just wanted to confirm that it was the desired behavior.
Thanks
