### ISSUE TITLE
Move sign-extending operators to "numeric" opcode prefix?

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/threads#86]
The [sign-extending operators](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md#new-sign-extending-operators) will have uses unrelated to threads. Would it make sense to move them out of the 0xfe prefix-byte space, perhaps into the anticipated ["numeric" prefix-byte space](https://github.com/WebAssembly/nontrapping-float-to-int-conversions/blob/master/proposals/nontrapping-float-to-int-conversion/Overview.md#encoding), 0xfc?

**Comment by lars-t-hansen** [comment]
The sign extend opcodes are not in the 0xFE space, they are single-byte opcodes (probably for this reason).  [spec](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md#spec-changes)

**Comment by sunfishcode** [comment]
Ah, you're right.
