### ISSUE TITLE
Separate out orthogonal proposals

### ISSUE THREAD

**Issue by binji** [WebAssembly/threads#88]
We decided in the [January 9th meeting](https://github.com/WebAssembly/meetings/blob/master/2018/CG-01-09.md) to separate out some orthogonal proposals from this proposal. Each should be its own proposal:

* [sign-extension operators](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md#new-sign-extending-operators)
* [importing/exporting mutable globals](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Globals.md)
* [conditional segment initialization](https://github.com/WebAssembly/threads/blob/master/proposals/threads/ConditionalSegmentInitialization.md)

**Comment by xtuc** [comment]
Do we just split this repo? or re-fork it from the main spec and apply commits or something?

**Comment by binji** [comment]
Yep, I'll do it today.

**Comment by binji** [comment]
OK, I've updated all the repos to spec/master, and copied the proposal docs as well.

FYI There is discussion about merging the [bulk-memory-operations proposal](https://github.com/WebAssembly/bulk-memory-operations) and [conditional-segment-initialization proposal](https://github.com/WebAssembly/conditional-segment-initialization) here: https://github.com/WebAssembly/conditional-segment-initialization/issues/1.
